language: python
python:
  - 2.7
  - 3.4
notifications:
  email: false

# Setup anaconda
before_install:
  - sudo apt-get update
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update -y -q conda
# Install packages
install:
  - conda create -q -n -y DeNovoPipeline python=$TRAVIS_PYTHON_VERSION numpy matplotlib click reportlab pandas
  - source activate DeNovoPipeline
  - python setup.py install

script:
  - deNovo_pipeline.py --help
  - scilifelab_denovo --help
