Pipelines:
 QCcontrol: ["fastqc", "abyss", "trimmomatic", "align"]
 assemble: ["abyss", "allpaths", "cabog",  "masurca", "soapdenovo", "spades", "trinity"]
 evaluete: ["align", "qaTools", "FRC"]
 align: []
Tools:
 fastqc:
  bin: /sw/apps/bioinfo/fastqc/0.10.1/milou/fastqc
  options: [--threads,  "16" ,  --outdir,  fastqc]
 trimmomatic:
  bin: /proj/a2010002/nobackup/tools/Trimmomatic-0.32/trimmomatic-0.32.jar
  options: [""]
 bwa:
  bin: /sw/apps/bioinfo/bwa/0.7.4/milou/bin/bwa
  options: ""
 picard:
  bin: /sw/apps/bioinfo/picard/1.92/milou/
  options: ""
 samtools:
  bin: /sw/apps/bioinfo/samtools/0.1.19/milou/bin/samtools
  options: ""
 abyss:
  bin: /sw/apps/bioinfo/abyss/1.3.5/milou/bin/
  options: [""]
